import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 3,
  tables: [
    tableSchema({
      name: 'attendance_logs',
      columns: [
        { name: 'remote_id', type: 'number', isOptional: true },
        { name: 'action', type: 'string' },
        { name: 'clocked_at', type: 'string' },
        { name: 'created_at', type: 'string', isOptional: true },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'accuracy_meters', type: 'number', isOptional: true },
        { name: 'verified', type: 'boolean', isOptional: true },
        { name: 'within_geofence', type: 'boolean', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'location_label', type: 'string', isOptional: true },
        { name: 'verification_status', type: 'string', isOptional: true },
        { name: 'distance_from_destination_meters', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'leave_requests',
      columns: [
        { name: 'remote_id', type: 'number', isOptional: true },
        { name: 'leave_type_id', type: 'number' },
        { name: 'start_date', type: 'string' },
        { name: 'end_date', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'reason', type: 'string' },
        { name: 'medical_report_url', type: 'string', isOptional: true },
        { name: 'days_requested', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'notifications',
      columns: [
        { name: 'remote_id', type: 'number', isOptional: true },
        { name: 'type', type: 'string' },
        { name: 'category', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'message', type: 'string' },
        { name: 'action_url', type: 'string', isOptional: true },
        { name: 'is_read', type: 'boolean' },
        { name: 'created_at', type: 'string' },
        { name: 'read_at', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'approval_tasks',
      columns: [
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'module', type: 'string' },
        { name: 'type_label', type: 'string' },
        { name: 'staff_name', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'subtitle', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'stage_name', type: 'string', isOptional: true },
        { name: 'submitted_at', type: 'string', isOptional: true },
        { name: 'waiting_days', type: 'number' },
        { name: 'can_act', type: 'boolean' },
        { name: 'approval_id', type: 'number', isOptional: true },
        { name: 'request_id', type: 'number', isOptional: true },
        { name: 'report_id', type: 'number', isOptional: true },
        { name: 'ppa_id', type: 'number', isOptional: true },
        { name: 'meta_string', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'oos_requests',
      columns: [
        { name: 'remote_id', type: 'number', isOptional: true },
        { name: 'reason_id', type: 'number' },
        { name: 'start_date', type: 'string' },
        { name: 'end_date', type: 'string' },
        { name: 'remarks', type: 'string', isOptional: true },
        { name: 'expected_deliverables', type: 'string', isOptional: true },
        { name: 'attachment_url', type: 'string', isOptional: true },
        { name: 'destination_name', type: 'string' },
        { name: 'destination_address', type: 'string', isOptional: true },
        { name: 'destination_latitude', type: 'number' },
        { name: 'destination_longitude', type: 'number' },
        { name: 'geofence_radius_meters', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'string', isOptional: true },
        { name: 'submitted_at', type: 'string', isOptional: true },
        { name: 'staff_name', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'leave_balances',
      columns: [
        { name: 'remote_id', type: 'number', isOptional: true },
        { name: 'leave_type_id', type: 'number' },
        { name: 'entitled_days', type: 'number' },
        { name: 'used_days', type: 'number' },
        { name: 'carried_over_days', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'leave_types',
      columns: [
        { name: 'remote_id', type: 'number', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'code', type: 'string' },
        { name: 'advance_notice_days', type: 'number', isOptional: true },
        { name: 'medical_report_after_days', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'profiles',
      columns: [
        { name: 'staff_id', type: 'number' },
        { name: 'user_data', type: 'string' },
        { name: 'staff_data', type: 'string' },
        { name: 'account_data', type: 'string' },
        { name: 'roles', type: 'string' },
        { name: 'permissions', type: 'string' },
      ],
    }),
  ],
});
