package seeders

// Generated from database/sql/legacy/01_legacy_source_tables.sql for Postgres-safe Ordinary KPI seeding.
// Do not edit by hand; regenerate from the legacy extract if MoH catalog changes.

type ordinaryKpiDef struct {
	Code                string
	ShortName           string
	IndicatorStatement  string
	Description         string
	Computation         string
	Numerator           string
	Denominator         string
	Frequency           string
	ComputationCategory string
	SubjectArea         *int
	CurrentTarget       *int
	IsCumulative        bool
	GaugeType           string
	LegacyJobID         string
}

type ordinaryJobDef struct {
	ExternalJobID string
	JobTitle      string
}

var ordinaryJobDefaults = []ordinaryJobDef{
	{"1", "Director"},
	{"2", "Specialist - Consultant"},
	{"3", "District Health Officer"},
	{"4", "Principal Medical Officer"},
	{"5", "Senior Medical Superintendent"},
	{"6", "Medical Superintendent"},
	{"7", "Nursing Supervisor -PNO-SNO"},
	{"8", "Nursing Officer"},
}

var ordinaryKpiDefaults = []ordinaryKpiDef{
	{
		Code: "125",
		ShortName: "Number of operational research studies proposed and initiated",
		IndicatorStatement: "Number of operational research studies proposed and initiated",
		Description: "",
		Computation: "",
		Numerator: "Number of operational research studies proposed and initiated",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(2),
		CurrentTarget: intPtr(1),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "126",
		ShortName: "Percentage of operational research recommendations implemented",
		IndicatorStatement: "Percentage of operational research recommendations implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of operational research recommendations implemented",
		Denominator: "Number of operational research recommendations",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(2),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "127",
		ShortName: "Percentage of vacant positions declared",
		IndicatorStatement: "Percentage of vacant positions declared",
		Description: "",
		Computation: "",
		Numerator: "Number of vacant positions declared",
		Denominator: "Number of vacant positions",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "128",
		ShortName: "Percentage of staff with performance management plans",
		IndicatorStatement: "Percentage of staff with performance management plans",
		Description: "",
		Computation: "",
		Numerator: "Number of staff with performance management plans",
		Denominator: "Number of staff",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "129",
		ShortName: "Percentage of staff with performance management contracts",
		IndicatorStatement: "Percentage of staff with performance management contracts",
		Description: "",
		Computation: "",
		Numerator: "Number of staff with performance management contracts",
		Denominator: "Number of staff",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "130",
		ShortName: "Percentage of staff appraised",
		IndicatorStatement: "Percentage of staff appraised",
		Description: "",
		Computation: "",
		Numerator: "Number of staff appraised",
		Denominator: "Number of staff due for appraisal",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "131",
		ShortName: "Average daily staff attendance to duty rate",
		IndicatorStatement: "Average daily staff attendance to duty rate",
		Description: "",
		Computation: "",
		Numerator: "Average daily staff attendance to duty rate",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "132",
		ShortName: "The Integrated Human Resource Information System (iHRIS) is updated",
		IndicatorStatement: "The Integrated Human Resource Information System (iHRIS) is updated",
		Description: "",
		Computation: "",
		Numerator: "The Integrated Human Resource Information System (iHRIS) is updated",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(1),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "133",
		ShortName: "Number of Reward and Sanctions Committee meetings held",
		IndicatorStatement: "Number of Reward and Sanctions Committee meetings held",
		Description: "",
		Computation: "",
		Numerator: "Number of Reward and Sanctions Committee meetings held",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(1),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "134",
		ShortName: "Percentage of Reward and Sanctions Committee recommendations implemented",
		IndicatorStatement: "Percentage of Reward and Sanctions Committee recommendations implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of Reward and Sanctions Committee recommendations implemented",
		Denominator: "Number of Reward and Sanctions Committee recommendations",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "135",
		ShortName: "Percentage of staff that needed medical care within the hospital means that are supported",
		IndicatorStatement: "Percentage of staff that needed medical care within the hospital means that are supported",
		Description: "",
		Computation: "",
		Numerator: "Number of staff that needed medical care within the hospital means that are supported",
		Denominator: "Number of staff that needed medical care within the hospital means",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "136",
		ShortName: "Percentage of staff welfare supported",
		IndicatorStatement: "Percentage of staff welfare supported",
		Description: "",
		Computation: "",
		Numerator: "Number of staff supported with welfare",
		Denominator: "Number of staff that needed welfare support",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "137",
		ShortName: "Percentage of staff provided with institutional accommodation",
		IndicatorStatement: "Percentage of staff provided with institutional accommodation",
		Description: "",
		Computation: "",
		Numerator: "Number of staff provided with institutional accommodation",
		Denominator: "Number  of staff eligible for institutional accommodation",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "138",
		ShortName: "Percentage of health-workers who have had additional formal in-service training   ",
		IndicatorStatement: "Percentage of health-workers who have had additional formal in-service training   ",
		Description: "",
		Computation: "",
		Numerator: "Number of health-workers who have had additional formal in-service training",
		Denominator: "Number of health-workers eligible/due for in-service training ",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "139",
		ShortName: "Percentage of clinical staff meeting the standard CPD hours",
		IndicatorStatement: "Percentage of clinical staff meeting the standard CPD hours",
		Description: "",
		Computation: "",
		Numerator: "Number of clinical  staff meeting the standard CPD hours",
		Denominator: "Number of clinical  staff",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(3),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "140",
		ShortName: "Percentage of new innovations/initiatives implemented by management",
		IndicatorStatement: "Percentage of new innovations/initiatives implemented by management",
		Description: "",
		Computation: "",
		Numerator: "Number of new innovations/initiatives implemented by management",
		Denominator: "Number of new innovations/initiatives expected to be implemented per Quarter.",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "141",
		ShortName: "Percentage of scheduled Hospital Board meetings conducted",
		IndicatorStatement: "Percentage of scheduled Hospital Board meetings conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of scheduled Hospital Board meetings conducted",
		Denominator: "Number of scheduled Hospital Board meetings",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "142",
		ShortName: "Percentage of Hospital Board recommendations implemented",
		IndicatorStatement: "Percentage of Hospital Board recommendations implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of Hospital Board recommendations implemented",
		Denominator: "Number of Hospital Board recommendations",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "143",
		ShortName: "Percentage of senior management meetings conducted",
		IndicatorStatement: "Percentage  of senior management meetings conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of senior management meetings conducted",
		Denominator: "Number of senior management meetings expected",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "144",
		ShortName: "Percentage of senior management meetings actions implemented",
		IndicatorStatement: "Percentage of senior management meetings actions implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of senior management meetings actions implemented",
		Denominator: "Number of senior management meetings actions",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "145",
		ShortName: "Percentage of departments fully utilizing the Integrated Electronic Medical Records (EMR) systems",
		IndicatorStatement: "Percentage of departments fully utilizing the Integrated Electronic Medical Records (EMR) systems",
		Description: "",
		Computation: "",
		Numerator: "Number of departments fully utilizing the Integrated Electronic Medical Records (EMR) systems",
		Denominator: "Number of departments due for utilizing the Integrated Electronic Medical Records (EMR) systems",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "146",
		ShortName: "Percentage of work-plan activities implemented",
		IndicatorStatement: "Percentage of work-plan activities implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of work-plan activities implemented",
		Denominator: "Number of work-plan activities",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "147",
		ShortName: "Percentage of audit recommendations addressed",
		IndicatorStatement: "Percentage of audit recommendations addressed",
		Description: "",
		Computation: "",
		Numerator: "Number of audit recommendations addressed",
		Denominator: "Number of audit recommendations",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "148",
		ShortName: "Percentage of planned procurements concluded",
		IndicatorStatement: "Percentage of planned procurements concluded",
		Description: "",
		Computation: "",
		Numerator: "Number of planned procurements concluded",
		Denominator: "Number of planned procurements",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(80),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "149",
		ShortName: "Amount of additional resources mobilized",
		IndicatorStatement: "Amount of additional resources mobilized",
		Description: "",
		Computation: "",
		Numerator: "Amount of additional resources mobilized",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(0),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "214",
		ShortName: "Percentage of departmental meetings attended",
		IndicatorStatement: "Percentage of departmental meetings attended",
		Description: "",
		Computation: "",
		Numerator: "Number of departmental meetings attended",
		Denominator: "Number of departmental meetings expected",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "215",
		ShortName: "Percentage of Technical Support supervision/mentorship conducted in the catchment area (GHs and HCIVs)",
		IndicatorStatement: "Percentage of Technical Support supervision/mentorship conducted in the catchment area (GHs and HCIVs)",
		Description: "",
		Computation: "",
		Numerator: "Number of Technical Support supervision/mentorship conducted in the catchment area (GHs and HCIVs).",
		Denominator: "Expected number of Technical Support supervision/mentorship conducted in the catchment area (GHs and",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(7),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "701",
		ShortName: "Percentage of patient file audits conducted for completeness of nursing care services",
		IndicatorStatement: "Percentage of patient file audits conducted for completeness of nursing care services",
		Description: "",
		Computation: "",
		Numerator: "Number of inpatient patient file audits conducted for nursing care services",
		Denominator: "Total Number of patients admitted during the quarter",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "702",
		ShortName: "Percentage of recommendations from the patient file record audits implemented",
		IndicatorStatement: "Percentage of recommendations from the patient file record audits implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of recommendations from the patient file record audits implemented",
		Denominator: "Number of recommendations from the patient file record audits",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "703",
		ShortName: "Percentage of the duty schedules implemented",
		IndicatorStatement: "Percentage of the duty schedules implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of duty schedules implemented",
		Denominator: "Number of duty schedules",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "703b",
		ShortName: "Percentage of proper Duty Hand over",
		IndicatorStatement: "Percentage of proper Duty Hand over",
		Description: "",
		Computation: "",
		Numerator: "Number of physical handovers",
		Denominator: "Total number of shifts in the Quarter",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "704",
		ShortName: "Percentage of emergency cases  attended to",
		IndicatorStatement: "Percentage of emergency cases  attended to",
		Description: "",
		Computation: "",
		Numerator: "Number of emergency cases conducted",
		Denominator: "Total number of emergencies in review period",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "705",
		ShortName: "Percentage  of Continuous Medical Education sessions  conducted",
		IndicatorStatement: "Percentage of Continuous Medical Education sessions  conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of CME sessions conducted",
		Denominator: "Total number planned CMEs",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "706",
		ShortName: "Percentage of WITs meetings conducted",
		IndicatorStatement: "Percentage of WITs meetings conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of WIT meetings conducted",
		Denominator: "Total number planned",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "707",
		ShortName: "Percentage of WITS meetings actions implemented",
		IndicatorStatement: "Percentage of WITS meetings actions implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of WITs meetings actions implemented",
		Denominator: "Number of actions from the WITs",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "708",
		ShortName: "Number of training and promotional needs assessment of nursing staff/midwifery",
		IndicatorStatement: "Number of training and promotional needs assessment of nursing staff/midwifery",
		Description: "",
		Computation: "",
		Numerator: "Number of training and promotional needs of nursing staff assessed",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(1),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "709",
		ShortName: "Percentage of  staff appraised",
		IndicatorStatement: "Percentage of  staff appraised",
		Description: "",
		Computation: "",
		Numerator: "Number of  staff appraised",
		Denominator: "Number of  staff due for appraisal",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "710",
		ShortName: "Percentage of senior/nursing officers  supervised and mentored",
		IndicatorStatement: "Percentage of senior/nursing officers  supervised and mentored",
		Description: "",
		Computation: "",
		Numerator: "Number of senior/nursing officers  supervised and mentored",
		Denominator: "Number of assigned senior/nursing officers for  supervision and mentorship",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "711",
		ShortName: "Percentage of students supervised and mentored",
		IndicatorStatement: "Percentage of students supervised and mentored",
		Description: "",
		Computation: "",
		Numerator: "Number of students supervised and mentored",
		Denominator: "Number of students assigned for supervision and mentorship",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "712",
		ShortName: "Number of operational research/innovation activities carried out/initiated",
		IndicatorStatement: "Number of operational research/innovation activities carried out/initiated",
		Description: "",
		Computation: "",
		Numerator: "Number of operational research/innovation activities carried out/initiated",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(2),
		CurrentTarget: intPtr(1),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "713",
		ShortName: "Number of actions taken to enforce the nursing care standards and professional code of conduct",
		IndicatorStatement: "Number of actions taken to enforce the nursing care standards and professional code of conduct",
		Description: "",
		Computation: "",
		Numerator: "Number of actions taken to enforce the nursing care standards and professional code of conduct",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(0),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "714",
		ShortName: "Percentage of approved work plan activities for nursing services implemented",
		IndicatorStatement: "Percentage of approved work plan activities for nursing services implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of approved work plan activities for nursing services implemented",
		Denominator: "Number of approved work plan activities for nursing services",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "716",
		ShortName: "Number of internal support supervision activities conducted",
		IndicatorStatement: "Number of internal support supervision activities conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of internal support supervision activities conducted",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(7),
		CurrentTarget: intPtr(1),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "717",
		ShortName: "Percentage of internal support supervision actions implemented",
		IndicatorStatement: "Percentage  of internal support supervision actions implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of internal support supervision actions implemented",
		Denominator: "Number of internal support supervision actions",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(7),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "7",
	},
	{
		Code: "103",
		ShortName: "The Average Length of Stay (ALS) in days",
		IndicatorStatement: "The Average Length of Stay (ALS) in days",
		Description: "",
		Computation: "",
		Numerator: "Average length of stay",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(2),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "104",
		ShortName: "Percentage of patients admitted that are referred out",
		IndicatorStatement: "Percentage of patients admitted that are referred out",
		Description: "",
		Computation: "",
		Numerator: "Number of patients admitted that are referred out",
		Denominator: "Number of patients admitted",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(0),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "105",
		ShortName: "Percentage Functionality of Accident and Emergency Services",
		IndicatorStatement: "Percentage Functionality of Accident and Emergency Services",
		Description: "",
		Computation: "",
		Numerator: "Number of fully functional parameters (1.Ambulance, 2.Team, 3.Equipment, 4.Medicines, 5.Supplies)",
		Denominator: "Number of parameters (1.Ambulance, 2.Team, 3.Equipment, 4.Medicines, 5.Supplies)",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "106",
		ShortName: "Number of specialized cases managed by the institution",
		IndicatorStatement: "Number of specialized cases managed by the institution",
		Description: "",
		Computation: "",
		Numerator: "Number of specialized cases managed by the institution",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(0),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "107",
		ShortName: "Number of specialized procedures conducted by the institution",
		IndicatorStatement: "Number of specialized procedures conducted by the institution",
		Description: "",
		Computation: "",
		Numerator: "Number of specialized procedures conducted by the institution",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(0),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "109",
		ShortName: "Number of specialized diagnostic procedures conducted",
		IndicatorStatement: "Number of specialized diagnostic procedures conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of specialized diagnostic procedures conducted",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(0),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "110",
		ShortName: "Percentage of clinical mentorship sessions undertaken",
		IndicatorStatement: "Percentage of clinical mentorship sessions undertaken",
		Description: "",
		Computation: "",
		Numerator: "Number of clinical mentorship sessions undertaken",
		Denominator: "Number of planned clinical mentorship sessions",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "111",
		ShortName: "Percentage of received blood units accounted for",
		IndicatorStatement: "Percentage of received blood units accounted for",
		Description: "",
		Computation: "",
		Numerator: "Number of blood units accounted for",
		Denominator: "Number of received blood units",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "112",
		ShortName: "Percentage of days the oxygen plant is functional",
		IndicatorStatement: "Percentage of days the oxygen plant is functional",
		Description: "",
		Computation: "",
		Numerator: "Number of days the oxygen plant is functional",
		Denominator: "Number of days within the period",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "113",
		ShortName: "Percentage of Hospital Deaths Notified",
		IndicatorStatement: "Percentage of Hospital Deaths Notified",
		Description: "",
		Computation: "",
		Numerator: "Number of Inpatient Deaths Notified",
		Denominator: "Total number of inpatient Deaths",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "113b",
		ShortName: "Percentage of hospital deaths medically certified",
		IndicatorStatement: "Percentage of hospital deaths medically certified",
		Description: "",
		Computation: "",
		Numerator: "Number of hospital deaths medically certified",
		Denominator: "Number of hospital deaths",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "114",
		ShortName: "Percentage of post-ops infection rate",
		IndicatorStatement: "Percentage of post-ops infection rate",
		Description: "",
		Computation: "",
		Numerator: "Number of post-ops infections",
		Denominator: "Number of operations",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(0),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "115",
		ShortName: "Availability of functional Hospital Quality Improvement Committee",
		IndicatorStatement: "Availability of functional Hospital Quality Improvement Committee",
		Description: "",
		Computation: "",
		Numerator: "Availability of functional Hospital Quality Improvement Committee",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(5),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "116",
		ShortName: "Percentage of wards/departments with a functional Ward/Work Improvement Team (WITs)",
		IndicatorStatement: "Percentage of wards/departments with a functional Ward/Work Improvement Team (WITs)",
		Description: "",
		Computation: "",
		Numerator: "Number of wards/departments with a functional Ward/Work Improvement Team (WITs)",
		Denominator: "Number of wards/departments expected to have a functional Ward/Work Improvement Team (WITs)",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "117",
		ShortName: "Client Satisfaction Assessment Surveys (exit interviews and community survey) conducted",
		IndicatorStatement: "Client Satisfaction Assessment Surveys (exit interviews and community survey) conducted",
		Description: "",
		Computation: "",
		Numerator: "Client Satisfaction Assessment Surveys conducted",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(1),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "118",
		ShortName: "Percentage of Client Satisfaction assessment actions implemented",
		IndicatorStatement: "Percentage of Client Satisfaction assessment actions implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of Client Satisfaction assessment actions implemented",
		Denominator: "Number of Client Satisfaction assessment actions",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "119",
		ShortName: "Number of Clinical Audit meetings conducted",
		IndicatorStatement: "Number of Clinical Audit meetings conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of Clinical Audit meetings conducted",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(0),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "120",
		ShortName: "Percentage of Clinical Audit Recommendations implemented",
		IndicatorStatement: "Percentage of Clinical Audit Recommendations implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of Clinical Audit Recommendations implemented",
		Denominator: "Number of Clinical Audit Recommendations",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "121",
		ShortName: "Number of Regional performance review meetings conducted",
		IndicatorStatement: "Number of Regional performance review meetings conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of Regional performance review meetings conducted",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(3),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "122",
		ShortName: "Percentage of Regional performance meeting actions implemented",
		IndicatorStatement: "Percentage of Regional performance meeting actions implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of Regional performance meeting actions implemented",
		Denominator: "Number of Regional performance meeting actions",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "123",
		ShortName: "Percentage of quarterly Hospital performance review meetings conducted",
		IndicatorStatement: "Percentage of quarterly Hospital performance review meetings conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of Hospital performance review meetings conducted",
		Denominator: "Expected Number of Hospital performance review meetings",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "124",
		ShortName: "Percentage of Hospital performance meeting actions implemented",
		IndicatorStatement: "Percentage of Hospital performance meeting actions implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of Hospital performance meeting actions implemented",
		Denominator: "Number of Hospital performance meeting actions",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "150",
		ShortName: "Percentage of allocated resources fully accounted for",
		IndicatorStatement: "Percentage of allocated resources fully accounted for",
		Description: "",
		Computation: "",
		Numerator: "Amount of allocated resources fully accounted for",
		Denominator: "Amount of allocated resources",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "151",
		ShortName: "Number of reconciliations of the 41 medicines and supplies conducted",
		IndicatorStatement: "Number of reconciliations of the 41 medicines and supplies conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of reconciliations of the 41 medicines and supplies conducted",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(5),
		CurrentTarget: intPtr(1),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "152",
		ShortName: "Health infrastructure inventory is updated",
		IndicatorStatement: "Health infrastructure inventory is updated",
		Description: "",
		Computation: "",
		Numerator: "Health infrastructure inventory is updated",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(6),
		CurrentTarget: intPtr(1),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "153",
		ShortName: "Percentage of non-functional medical equipment disposed off",
		IndicatorStatement: "Percentage of non-functional medical equipment disposed off",
		Description: "",
		Computation: "",
		Numerator: "Number of non-functional medical equipment disposed off",
		Denominator: "Number of non-functional medical equipment due for  disposal",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(6),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "154",
		ShortName: "Percentage of GHs and HC-Ivs supervised",
		IndicatorStatement: "Percentage of GHs and HC-Ivs supervised",
		Description: "",
		Computation: "",
		Numerator: "Number of GHs and HC-Ivs supervised",
		Denominator: "Number of GHs and HC-Ivs",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(7),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "155",
		ShortName: "Percentage of Technical support supervision visits recommendations to the hospital implemented",
		IndicatorStatement: "Percentage of Technical support supervision visits recommendations to the hospital implemented",
		Description: "",
		Computation: "",
		Numerator: "Number of Technical support supervision visits recommendations to the hospital implemented",
		Denominator: "Number of Technical support supervision visits recommendations to the hospital",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(7),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "156",
		ShortName: "Percentage of departments with standard hand washing/hygiene facilities",
		IndicatorStatement: "Percentage of departments with standard hand washing/hygiene facilities",
		Description: "",
		Computation: "",
		Numerator: "Number of departments with hand washing/hygiene facilities",
		Denominator: "Number of departments",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(8),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "157",
		ShortName: "Protected health care waste disposal facility available",
		IndicatorStatement: "Protected health care waste disposal facility available",
		Description: "",
		Computation: "",
		Numerator: "Protected health care waste disposal facility available",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(8),
		CurrentTarget: intPtr(1),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "1",
	},
	{
		Code: "201",
		ShortName: "Percentage  of conducted specialized procedures participated in",
		IndicatorStatement: "Percentage of conducted specialized procedures participated in",
		Description: "",
		Computation: "",
		Numerator: "Number of conducted specialized procedures participated in",
		Denominator: "Number of specialized procedures conducted",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(0),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "202",
		ShortName: "Percentage of functional specialized outpatient clinics",
		IndicatorStatement: "Percentage of functional specialized outpatient clinics",
		Description: "",
		Computation: "",
		Numerator: "Number of functional specialized outpatient clinics",
		Denominator: "Number of specialized outpatient clinics expected to be functional",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(0),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "203",
		ShortName: "Percentage of ward rounds participated in",
		IndicatorStatement: "Percentage of ward rounds participated in",
		Description: "",
		Computation: "",
		Numerator: "Number of ward rounds participated in",
		Denominator: "Number of ward rounds conducted",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "204",
		ShortName: "Percentage of emergency duties attended to",
		IndicatorStatement: "Percentage of emergency duties attended to",
		Description: "",
		Computation: "",
		Numerator: "Number of emergency duties attended to",
		Denominator: "Total no. of emergency duties",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "204b",
		ShortName: "Percentage of emergency patients attended to",
		IndicatorStatement: "Percentage of emergency patients attended to",
		Description: "",
		Computation: "",
		Numerator: "Number of emergency patients attended to",
		Denominator: "Total no. of emergency patients",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(50),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "205",
		ShortName: "Percentage of Continuous Medical Education (CME) sessions conducted",
		IndicatorStatement: "Percentage of Continuous Medical Education (CME) sessions conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of CME sessions conducted",
		Denominator: "Number of CME sessions  expected",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "205b",
		ShortName: "Percentage of Continuous Medical Education (CME) sessions attended",
		IndicatorStatement: "Percentage of Continuous Medical Education (CME) sessions attended",
		Description: "",
		Computation: "",
		Numerator: "Number of CME sessions attended",
		Denominator: "Number of CME sessions conducted",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "206",
		ShortName: "Number of staff training and professional growth needs identified",
		IndicatorStatement: "Number of staff training and professional growth needs identified",
		Description: "",
		Computation: "",
		Numerator: "Number of staff training and professional growth needs identified",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(0),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "206b",
		ShortName: "Percentage of staff trained on Management standards and guidelines for clinical proficiency",
		IndicatorStatement: "Percentage of staff trained on Management standards and guidelines for clinical proficiency",
		Description: "",
		Computation: "",
		Numerator: "Number of staff trained",
		Denominator: "Number of staff expected to be trained",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(50),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "207",
		ShortName: "Number of Clinical Audits conducted",
		IndicatorStatement: "Number of Clinical Audits conducted",
		Description: "",
		Computation: "",
		Numerator: "Number of Clinical Audits conducted",
		Denominator: "",
		Frequency: "Quarterly",
		ComputationCategory: "Value",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(1),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "207b",
		ShortName: "Percentage of deaths occurring in the department and recorded in DHIS2 that are medically certified",
		IndicatorStatement: "Percentage of deaths occurring in the department and recorded in DHIS2 that are medically certified",
		Description: "",
		Computation: "",
		Numerator: "No. of deaths notified and medically certified ",
		Denominator: "Total no. of deaths reported in the department ",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "208",
		ShortName: "Percentage of QI Committee meetings attended",
		IndicatorStatement: "Percentage of QI Committee meetings attended",
		Description: "",
		Computation: "",
		Numerator: "Number of QI Committee meetings supported (attended)",
		Denominator: "Number of QI Committee meetings expected in the quarter",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "209",
		ShortName: "Percentage of assigned staff appraised",
		IndicatorStatement: "Percentage of assigned staff appraised",
		Description: "",
		Computation: "",
		Numerator: "Number of assigned staff appraised",
		Denominator: "Number of assigned staff due for appraisal",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "210",
		ShortName: "Percentage of assigned staff supervised and mentored",
		IndicatorStatement: "Percentage of assigned staff supervised and mentored",
		Description: "",
		Computation: "",
		Numerator: "Number of assigned staff supervised and mentored",
		Denominator: "Number of assigned staff",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "211",
		ShortName: "Percentage of monthly data reviews and data-driven actions undertaken",
		IndicatorStatement: "Percentage of monthly data reviews and data-driven actions undertaken",
		Description: "",
		Computation: "",
		Numerator: "Number of data reviews and data-driven actions undertaken",
		Denominator: "Expected number of data reviews",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(1),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "212",
		ShortName: "Percentage of operational research activities/innovations carried out",
		IndicatorStatement: "Percentage of operational research activities/innovations carried out",
		Description: "",
		Computation: "",
		Numerator: "Number of operational research activities/innovations carried out",
		Denominator: "Number of operational research activities/innovations expected",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(2),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
	{
		Code: "213",
		ShortName: "Percentage of Management/Hospital committee meetings attended",
		IndicatorStatement: "Percentage of Management/Hospital committee meetings attended",
		Description: "",
		Computation: "",
		Numerator: "Number of Management/ Hospital committee meetings attended",
		Denominator: "Number of Management/ Hospital committee meetings expected",
		Frequency: "Quarterly",
		ComputationCategory: "Ratio",
		SubjectArea: intPtr(4),
		CurrentTarget: intPtr(100),
		IsCumulative: false,
		GaugeType: "ascending_scale",
		LegacyJobID: "2",
	},
}
