// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/leave/approval-stages": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "List leave approval stages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Create leave approval stage",
                "parameters": [
                    {
                        "description": "Approval stage",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveApprovalStage"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/approval-stages/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Update leave approval stage",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Stage ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Approval stage",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveApprovalStage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/entitlements": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "List leave entitlements",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Create leave entitlement",
                "parameters": [
                    {
                        "description": "Entitlement",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveEntitlement"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/entitlements/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Update leave entitlement",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entitlement ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Entitlement",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveEntitlement"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Delete leave entitlement",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entitlement ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/settings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Get leave policy settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Update leave policy settings",
                "parameters": [
                    {
                        "description": "Leave settings",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.leaveSettingsBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "List all leave types (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Create leave type",
                "parameters": [
                    {
                        "description": "Leave type",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveType"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/types/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Update leave type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Leave type ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Leave type",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Deactivate leave type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Leave type ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/rbac/grant-permission": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Grant permission to role",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "List permissions",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/roles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "List roles",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/roles/{id}/scopes": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Configure data scope for a role",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Create application user (database admin)",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/users/{id}/roles": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Assign role to user",
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Revoke role from user",
                "responses": {}
            }
        },
        "/api/v1/auth/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Change own password",
                "responses": {}
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate and receive JWT",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.loginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Invalidate JWT",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user profile with roles and permissions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh JWT",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/attendance/clock": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Compares GPS position against approved out-of-station destination when applicable",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-attendance"
                ],
                "summary": "Clock in or out with GPS",
                "parameters": [
                    {
                        "description": "Clock event",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.clockBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/attendance/clocks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-attendance"
                ],
                "summary": "List my attendance clocks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "From date YYYY-MM-DD",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "To date YYYY-MM-DD",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/leave/approvals/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-supervisor"
                ],
                "summary": "Supervisor approve/reject leave",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Leave approval ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Decision",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.approvalBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/leave/balances": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-leave"
                ],
                "summary": "Get leave balances",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Calendar year",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/leave/config": {
            "get": {
                "description": "Settings, types, entitlements, and approval stages loaded from database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-leave"
                ],
                "summary": "Full dynamic leave configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/leave/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-leave"
                ],
                "summary": "List my leave requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Per leave.md: submit at least 2 weeks in advance; sick leave \u003e2 days needs medical report",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-leave"
                ],
                "summary": "Create leave request (self-service)",
                "parameters": [
                    {
                        "description": "Leave request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.leaveRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/leave/types": {
            "get": {
                "description": "Returns leave types from database configuration (not hardcoded)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-leave"
                ],
                "summary": "List active leave types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/out-of-station/approvals/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-supervisor"
                ],
                "summary": "Supervisor approve/reject out-of-station request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Out-of-station approval ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Decision",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.approvalBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/out-of-station/reasons": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-out-of-station"
                ],
                "summary": "List out-of-station reasons",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/out-of-station/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-out-of-station"
                ],
                "summary": "List my out-of-station requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mirrors attend/requests/newRequest with map-picked destination coordinates for GPS verification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-out-of-station"
                ],
                "summary": "Create out-of-station request",
                "parameters": [
                    {
                        "description": "Out of station request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.oosRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/swagger/{any}": {
            "get": {
                "summary": "Swagger API documentation",
                "responses": {}
            }
        }
    },
    "definitions": {
        "controllers.approvalBody": {
            "type": "object",
            "properties": {
                "approve": {
                    "type": "boolean"
                },
                "comments": {
                    "type": "string"
                }
            }
        },
        "controllers.clockBody": {
            "type": "object",
            "properties": {
                "accuracy_meters": {
                    "type": "number"
                },
                "clock_type": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "location_label": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "controllers.leaveRequestBody": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "leave_type_id": {
                    "type": "integer"
                },
                "medical_report_url": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "submit": {
                    "type": "boolean"
                }
            }
        },
        "controllers.leaveSettingsBody": {
            "type": "object",
            "properties": {
                "advance_notice_days": {
                    "type": "integer"
                },
                "allow_carry_over": {
                    "type": "boolean"
                },
                "carry_over_deadline": {
                    "type": "string"
                },
                "clock_window_morning": {
                    "type": "string"
                },
                "vesting_day": {
                    "type": "integer"
                },
                "vesting_month": {
                    "type": "integer"
                },
                "work_hours": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "controllers.loginBody": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "controllers.oosRequestBody": {
            "type": "object",
            "properties": {
                "attachment_url": {
                    "type": "string"
                },
                "destination_address": {
                    "type": "string"
                },
                "destination_latitude": {
                    "type": "number"
                },
                "destination_longitude": {
                    "type": "number"
                },
                "destination_name": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "geofence_radius_meters": {
                    "type": "integer"
                },
                "reason_id": {
                    "type": "integer"
                },
                "remarks": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "submit": {
                    "type": "boolean"
                }
            }
        },
        "github_com_goravel_framework_support_carbon.DateTime": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "models.LeaveApprovalStage": {
            "type": "object",
            "properties": {
                "approverRole": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer",
                    "format": "int32"
                },
                "updated_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                }
            }
        },
        "models.LeaveEntitlement": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                },
                "daysPerYear": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "leaveTypeID": {
                    "type": "integer"
                },
                "medicalReportAfterDays": {
                    "type": "integer"
                },
                "requiresHrFinalization": {
                    "type": "boolean"
                },
                "salaryGrade": {
                    "type": "string"
                },
                "updated_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                }
            }
        },
        "models.LeaveType": {
            "type": "object",
            "properties": {
                "advanceNoticeDays": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                },
                "description": {
                    "type": "string"
                },
                "eligibilityNotes": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "maxDaysPerRequest": {
                    "type": "integer"
                },
                "maxDaysPerYear": {
                    "type": "integer"
                },
                "medicalReportAfterDays": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "requiresHrApproval": {
                    "type": "boolean"
                },
                "requiresSupervisorApproval": {
                    "type": "boolean"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "updated_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Bearer token. Format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3030",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MoH Uganda PMS API",
	Description:      "Performance Management System API for Ministry of Health Uganda. Mobile self-service endpoints for leave, out-of-station, and GPS attendance clocking.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
