// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/analytics/doris/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Sync analytics warehouse",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/analytics/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Analytics (Doris) connection status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/kpi/assignment-targets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Facility types, facilities, departments (with facility type context), and job titles.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-kpi"
                ],
                "summary": "Assignable targets for KPI mapping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/kpi/assignments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-kpi"
                ],
                "summary": "List KPI assignments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Assign one or more KPIs to facility_type, facility, department, job, or staff.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-kpi"
                ],
                "summary": "Create KPI assignment(s)",
                "parameters": [
                    {
                        "description": "kpi_ids, assignable_type, target ids",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/kpi/kpis": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-kpi"
                ],
                "summary": "List KPI catalog",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/approval-stages": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "List leave approval stages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Create leave approval stage",
                "parameters": [
                    {
                        "description": "Approval stage",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveApprovalStage"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/approval-stages/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Update leave approval stage",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Stage ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Approval stage",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveApprovalStage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/balances": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "List staff leave balances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/entitlements": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "List leave entitlements",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Create leave entitlement",
                "parameters": [
                    {
                        "description": "Entitlement",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveEntitlement"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/entitlements/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Update leave entitlement",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entitlement ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Entitlement",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveEntitlement"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Delete leave entitlement",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entitlement ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/overview": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Leave admin overview metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "List leave requests (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/requests/{id}/finalize": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Moves a fully approved request to finalized status. Requires leave.config.manage.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "HR finalize approved leave request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Leave request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/settings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Get leave policy settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Update leave policy settings",
                "parameters": [
                    {
                        "description": "Leave settings",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.leaveSettingsBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "List all leave types (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Create leave type",
                "parameters": [
                    {
                        "description": "Leave type",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveType"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/leave/types/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Update leave type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Leave type ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Leave type",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LeaveType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-leave"
                ],
                "summary": "Deactivate leave type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Leave type ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/lists/departments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-lists"
                ],
                "summary": "List departments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/lists/facilities": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-lists"
                ],
                "summary": "List facilities (paginated)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/lists/refresh-catalog": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-lists"
                ],
                "summary": "Refresh facility/institution type catalog from facilities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/lists/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-lists"
                ],
                "summary": "Org catalog summary counts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/notifications/send-reminders": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-settings"
                ],
                "summary": "Send configured notification reminders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/performance/settings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-performance"
                ],
                "summary": "Performance reporting settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/rbac/audit-logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "List RBAC audit logs",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/audit-logs/{id}/recover": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Recover a dangerous RBAC action",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/grant-permission": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Grant permission to role",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "List permissions",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/revoke-permission": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Revoke permission from role",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/roles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "List roles",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/roles/{code}/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "List permissions granted to a role",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/roles/{id}/scopes": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Configure data scope for a role",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/scope-options": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "District and facility options for user data scope",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "List application users",
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Create application user (database admin)",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/users/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Update application user",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/users/{id}/link-staff-by-email": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Link user to staff record by matching email",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/users/{id}/permissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "List direct permissions granted to a user",
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Grant permission directly to user",
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Revoke direct permission from user",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/users/{id}/reset-authenticator": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Admin override — reset user authenticator",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/users/{id}/roles": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Assign role to user",
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Revoke role from user",
                "responses": {}
            }
        },
        "/api/v1/admin/rbac/users/{id}/send-activation": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-rbac"
                ],
                "summary": "Send account activation email for linked staff",
                "responses": {}
            }
        },
        "/api/v1/admin/settings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-settings"
                ],
                "summary": "Get system settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-settings"
                ],
                "summary": "Update system settings group",
                "parameters": [
                    {
                        "description": "group + payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/staff": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-staff"
                ],
                "summary": "Staff directory (paginated)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/staff/{id}/hr-profile": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "HR department override, contact fields, leave management flag (is_leave_manager).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-staff"
                ],
                "summary": "Update staff HR profile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Staff ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "hr_department_id, hr_email, is_leave_manager, etc.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/staff/{id}/supervisors": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-staff"
                ],
                "summary": "Set supervisor chain (up to 3)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Staff ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "supervisors: [{sequence, supervisor_staff_id}]",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/activation/complete": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Complete account activation",
                "responses": {}
            }
        },
        "/api/v1/auth/activation/{token}": {
            "get": {
                "tags": [
                    "auth"
                ],
                "summary": "Preview activation token",
                "responses": {}
            }
        },
        "/api/v1/auth/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Change own password",
                "responses": {}
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate and receive JWT",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.loginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login/totp": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Complete login with authenticator code",
                "responses": {}
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Invalidate JWT",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user profile with roles and permissions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/profile": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Update profile photo and/or signature",
                "responses": {}
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh JWT",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/request-activation": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Request account activation email for staff",
                "responses": {}
            }
        },
        "/api/v1/auth/request-password-reset": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Request password reset email",
                "responses": {}
            }
        },
        "/api/v1/auth/totp/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Confirm authenticator enrollment",
                "responses": {}
            }
        },
        "/api/v1/auth/totp/disable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Disable authenticator",
                "responses": {}
            }
        },
        "/api/v1/auth/totp/enroll": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Start authenticator enrollment",
                "responses": {}
            }
        },
        "/api/v1/auth/totp/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticator status",
                "responses": {}
            }
        },
        "/api/v1/config": {
            "get": {
                "description": "Branding and client-safe settings for the web app.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Public client configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard/department-head": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Department head dashboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard/health-worker": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Staff dashboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard/hr-manager": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "HR / director / executive dashboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard/supervisor": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Supervisor dashboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/files": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Download an uploaded attachment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relative path under uploads/",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "Returns service status. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "API health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/hrm-attend/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Sync HRM attendance feed",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/ihris/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Trigger iHRIS staff sync",
                "parameters": [
                    {
                        "description": "Optional batch options (run_id, start_page, pages_per_batch)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/ihris/sync/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "iHRIS sync run status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/approvals/inbox": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Pending leave, out-of-station, PPA, and appraisal items for the signed-in approver. Requires a linked staff record.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "approvals"
                ],
                "summary": "Unified approvals inbox",
                "responses": {
                    "200": {
                        "description": "items, stats (counts and average approval time)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "User not linked to staff",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/attendance/clock": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Compares GPS position against approved out-of-station destination when applicable",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-attendance"
                ],
                "summary": "Clock in or out with GPS",
                "parameters": [
                    {
                        "description": "Clock event",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.clockBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/attendance/clocks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-attendance"
                ],
                "summary": "List my attendance clocks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "From date YYYY-MM-DD",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "To date YYYY-MM-DD",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/leave/approvals/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-supervisor"
                ],
                "summary": "Supervisor approve/reject leave",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Leave approval ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Decision",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.approvalBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/leave/balances": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-leave"
                ],
                "summary": "Get leave balances",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Calendar year",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/leave/config": {
            "get": {
                "description": "Settings, types, entitlements, and approval stages loaded from database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-leave"
                ],
                "summary": "Full dynamic leave configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/leave/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-leave"
                ],
                "summary": "List my leave requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Per leave.md: submit at least 2 weeks in advance; sick leave \u003e2 days needs medical report",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-leave"
                ],
                "summary": "Create leave request (self-service)",
                "parameters": [
                    {
                        "description": "Leave request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.leaveRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/leave/types": {
            "get": {
                "description": "Returns leave types from database configuration (not hardcoded)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-leave"
                ],
                "summary": "List active leave types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/out-of-station/approvals/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-supervisor"
                ],
                "summary": "Supervisor approve/reject out-of-station request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Out-of-station approval ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Decision",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.approvalBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/out-of-station/reasons": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-out-of-station"
                ],
                "summary": "List out-of-station reasons",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/out-of-station/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-out-of-station"
                ],
                "summary": "List my out-of-station requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mirrors attend/requests/newRequest with map-picked destination coordinates for GPS verification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-out-of-station"
                ],
                "summary": "Create out-of-station request",
                "parameters": [
                    {
                        "description": "Out of station request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.oosRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/performance/kpis/grouped": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-performance"
                ],
                "summary": "Assigned KPIs grouped by function",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/performance/overall-rating": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-performance"
                ],
                "summary": "Overall performance rating for the authenticated staff member",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/performance/ppa/review": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-performance"
                ],
                "summary": "Review submitted PPA",
                "parameters": [
                    {
                        "description": "ppa_id, approve, comments",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/performance/status-report": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-performance"
                ],
                "summary": "Scoped PPA + quarterly submission/approval status with scores",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/performance/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-performance"
                ],
                "summary": "PPA and KPI summary for current staff",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mobile/performance/windows": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile-performance"
                ],
                "summary": "Current performance reporting windows",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List in-app notifications",
                "responses": {}
            }
        },
        "/api/v1/notifications/read-all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Mark all notifications as read",
                "responses": {}
            }
        },
        "/api/v1/notifications/unread-count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Unread in-app notification count",
                "responses": {}
            }
        },
        "/api/v1/notifications/{id}/read": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Mark notification as read",
                "responses": {}
            }
        },
        "/api/v1/uploads": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Upload a leave/travel attachment",
                "parameters": [
                    {
                        "description": "Base64 data URL",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.uploadBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/services.UploadedFile"
                        }
                    }
                }
            }
        },
        "/swagger/{any}": {
            "get": {
                "description": "Interactive OpenAPI documentation for the MoH Uganda Performance Management System.",
                "tags": [
                    "documentation"
                ],
                "summary": "Swagger API documentation",
                "responses": {}
            }
        }
    },
    "definitions": {
        "controllers.approvalBody": {
            "type": "object",
            "properties": {
                "approve": {
                    "type": "boolean"
                },
                "comments": {
                    "type": "string"
                }
            }
        },
        "controllers.clockBody": {
            "type": "object",
            "properties": {
                "accuracy_meters": {
                    "type": "number"
                },
                "clock_type": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "location_label": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "controllers.leaveRequestBody": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "leave_type_id": {
                    "type": "integer"
                },
                "medical_report_url": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "submit": {
                    "type": "boolean"
                }
            }
        },
        "controllers.leaveSettingsBody": {
            "type": "object",
            "properties": {
                "advance_notice_days": {
                    "type": "integer"
                },
                "allow_carry_over": {
                    "type": "boolean"
                },
                "block_past_dates": {
                    "type": "boolean"
                },
                "carry_over_deadline": {
                    "type": "string"
                },
                "clock_window_morning": {
                    "type": "string"
                },
                "enforce_advance_notice": {
                    "type": "boolean"
                },
                "exempt_sick_leave_advance_notice": {
                    "type": "boolean"
                },
                "vesting_day": {
                    "type": "integer"
                },
                "vesting_month": {
                    "type": "integer"
                },
                "work_hours": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "controllers.loginBody": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "controllers.oosRequestBody": {
            "type": "object",
            "properties": {
                "attachment_url": {
                    "type": "string"
                },
                "destination_address": {
                    "type": "string"
                },
                "destination_latitude": {
                    "type": "number"
                },
                "destination_longitude": {
                    "type": "number"
                },
                "destination_name": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "expected_deliverables": {
                    "type": "string"
                },
                "geofence_radius_meters": {
                    "type": "integer"
                },
                "reason_id": {
                    "type": "integer"
                },
                "remarks": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "submit": {
                    "type": "boolean"
                }
            }
        },
        "controllers.uploadBody": {
            "type": "object",
            "properties": {
                "data_url": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                }
            }
        },
        "github_com_goravel_framework_support_carbon.DateTime": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "models.LeaveApprovalStage": {
            "type": "object",
            "properties": {
                "approverRole": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isRequired": {
                    "type": "boolean"
                },
                "jobTitleID": {
                    "type": "integer"
                },
                "jobTitleMatch": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer",
                    "format": "int32"
                },
                "skipIfUnresolved": {
                    "type": "boolean"
                },
                "stageType": {
                    "type": "string"
                },
                "supervisorSequence": {
                    "type": "integer"
                },
                "updated_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                },
                "workflowProfileCode": {
                    "type": "string"
                }
            }
        },
        "models.LeaveEntitlement": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                },
                "daysPerYear": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "leaveTypeID": {
                    "type": "integer"
                },
                "medicalReportAfterDays": {
                    "type": "integer"
                },
                "requiresHrFinalization": {
                    "type": "boolean"
                },
                "salaryGrade": {
                    "type": "string"
                },
                "updated_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                }
            }
        },
        "models.LeaveType": {
            "type": "object",
            "properties": {
                "advance_notice_days": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                },
                "description": {
                    "type": "string"
                },
                "eligibility_notes": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "max_days_per_request": {
                    "type": "integer"
                },
                "max_days_per_year": {
                    "type": "integer"
                },
                "medical_report_after_days": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "requires_hr_approval": {
                    "type": "boolean"
                },
                "requires_supervisor_approval": {
                    "type": "boolean"
                },
                "sort_order": {
                    "type": "integer"
                },
                "updated_at": {
                    "$ref": "#/definitions/github_com_goravel_framework_support_carbon.DateTime"
                },
                "workflow_profile_code": {
                    "type": "string"
                }
            }
        },
        "services.UploadedFile": {
            "type": "object",
            "properties": {
                "mime_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Bearer token. Format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Authentication, session, profile, and two-factor (TOTP)",
            "name": "auth"
        },
        {
            "description": "Unified inbox for pending leave, out-of-station, and performance approvals",
            "name": "approvals"
        },
        {
            "description": "Staff leave balances, types, and request submission",
            "name": "mobile-leave"
        },
        {
            "description": "Supervisor leave and out-of-station approval actions",
            "name": "mobile-supervisor"
        },
        {
            "description": "Out-of-station travel requests",
            "name": "mobile-oos"
        },
        {
            "description": "Attendance clock events with optional GPS coordinates",
            "name": "mobile-attendance"
        },
        {
            "description": "Performance planning (PPA), quarterly reports, and appraisals",
            "name": "mobile-performance"
        },
        {
            "description": "Role-scoped dashboard metrics and drill-down data",
            "name": "dashboard"
        },
        {
            "description": "Leave administration — balances, requests, workflow stages, HR finalize",
            "name": "admin-leave"
        },
        {
            "description": "KPI catalog, assignments by facility type / facility / department / job / staff",
            "name": "admin-kpi"
        },
        {
            "description": "Staff management — HR enrichment, supervisors, activation",
            "name": "admin-staff"
        },
        {
            "description": "Organisation reference lists and catalog maintenance",
            "name": "admin-lists"
        },
        {
            "description": "Access control — users, roles, permissions, data scopes, audit log",
            "name": "admin-rbac"
        },
        {
            "description": "System settings — integrations, email, notifications, performance windows",
            "name": "admin-settings"
        },
        {
            "description": "Performance reporting configuration",
            "name": "admin-performance"
        },
        {
            "description": "iHRIS sync, HRM attendance, analytics (Doris)",
            "name": "integrations"
        },
        {
            "description": "In-app notifications for the signed-in user",
            "name": "notifications"
        },
        {
            "description": "Health check and public configuration",
            "name": "system"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "MoH Uganda PMS API",
	Description:      "Ministry of Health Uganda — Performance Management System (iHRIS-integrated).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
